CREATE TABLESPACE user_exam
DATAFILE 'C:/Exam/user_exam.dbf' 
SIZE 10M;

SELECT * 
FROM v$logfile;

SELECT tablespace_name, status, contents FROM dba_tablespaces;

CREATE TABLE MEMBER_LOG
(
    LOGNO NUMBER,
    MEMBERNO NUMBER,
    LOGIN DATE,
    LOGOUT DATE
);

CREATE TABLE MEMBER
(  
    MEMBERNO NUMBER,
    ID VARCHAR2(30) NOT NULL UNIQUE,
    PW VARCHAR2(30),
    NAME VARCHAR2(30),
    PHONE VARCHAR2(15)
);

ALTER TABLE MEMBER_LOG ADD CONSTRAINT MEMBER_LOG_PK PRIMARY KEY(LOGNO);
ALTER TABLE MEMBER_LOG ADD CONSTRAINT MEMBER_LOG_MEMBER_fk FOREIGN KEY(MEMBERNO) REFERENCES MEMBER(MEMBERNO);
ALTER TABLE MEMBER ADD CONSTRAINT MEMBER_PK PRIMARY KEY(MEMBERNO);
    
SELECT * FROM dba_objects;

  
    
    
    
    
    
